name: Build & Deploy
on:
  workflow_dispatch
jobs:
  web-deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
    - name: Checkout the code
      uses: actions/checkout@v2.3.2
    - name: Setup the Node.js
      uses: actions/setup-node@master
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Installing project dependencies
      run: npm ci
    - name: Building the project
      run: npm run build
    #- name: Set directory permissions
    #  run: chmod -R 777 storage bootstrap/cache
    - name: Upload files to shared hosting
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: ${{ secrets.FTP_DEPLOY_HOST}}
        username: ${{ secrets.FTP_DEPLOY_USER}}
        password: ${{ secrets.FTP_DEPLOY_PASSWORD}}
        server-dir: ${{ secrets.FTP_DEPLOY_BASE_PATH}}/aukro/
        dangerous-clean-slate: true
        local-dir: ./dist/photo-fetcher/
