name: Deploy Site on push
on:
  workflow_dispatch
jobs:
  web-deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
    - name: Checkout the code
      uses: actions/checkout@v2.3.2
    - name: Setup the Node.js
      uses: actions/setup-node@master
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Installing project dependencies
      run: npm ci
    - name: Building the project
      run: npm run build
    #- name: Copy .env
    #  run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    #- name: Install Dependencies
    #  run: composer update --ignore-platform-reqs
    #- name: Generate key
    #  run: php artisan key:generate
    #- name: Set directory permissions
    #  run: chmod -R 777 storage bootstrap/cache
    #- name: Upload files to shared hosting
    #  uses: SamKirkland/FTP-Deploy-Action@4.0.0
    #  with:
    #    server: ${{ secrets.LARAVEL_SITE_SERVER}}
    #    username: ${{ secrets.LARAVEL_SITE_USER}}
    #    password: ${{ secrets.LARAVEL_SITE_PASS}}
